// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpbwsjxldpvgmbngisud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwYndzanhsZHB2Z21ibmdpc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTY4ODEsImV4cCI6MjA3MDU3Mjg4MX0.MATue_UgEh2SyXLE4TKhCwi-IQN3KFcI_ekZOXFQFAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});